# -*- coding: utf-8 -*-
"""Comparação de escolas sem esgoto e sem energia e Rurais

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eawhiPUOQw5Loc-RxJ1faXQCoTxznJk_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#carregando arquivos do PC
from google.colab import files
uploaded = files.upload()

escolas = pd.read_excel('ESGOTO E ENERGIA.xlsx')

escolas.head(27)

estados = escolas['ESTADOS']
energia = escolas['SEM ENERGIA']
esgoto = escolas['SEM ESGOTO']

largura_barra = 0.45
indices = np.arange(len(estados))

plt.bar(indices,energia, largura_barra, label='Escolas Sem Energia')
plt.bar(indices + largura_barra, esgoto, largura_barra, label='Escolas sem esgoto')

plt.xlabel('ESTADOS')
plt.ylabel('ESCOLAS')
plt.title('Comparação de Escolas sem energia e Esgoto')
plt.xticks(indices + largura_barra / 2, estados, rotation=45)  # Rótulos no eixo x (com rotação para melhor legibilidade)
plt.legend(fontsize=16)

plt.tight_layout()
plt.show()

Estados = escolas['ESTADOS']
Energia = escolas['RURAL']
Esgoto = escolas['SEM ESGOTO RURAL']

largura_barra = 0.45
indices = np.arange(len(estados))

plt.bar(indices,Energia, largura_barra, label='Escolas Rurais sem Energia')
plt.bar(indices + largura_barra, Esgoto, largura_barra, label='Escolas Rurais sem esgoto')

plt.xlabel('ESTADOS')
plt.ylabel('ESCOLAS')
plt.title('Comparação de Escolas Rurais sem energia e Esgoto')
plt.xticks(indices + largura_barra / 2, estados, rotation=45)  # Rótulos no eixo x (com rotação para melhor legibilidade)
plt.legend(fontsize=16)

plt.tight_layout()
plt.show()

