# -*- coding: utf-8 -*-
"""Comparação de Escolas Rurais e S/ Esgoto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uCaHCvIkkAB2SLbbxvkxbN9mK1RqRteV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

esgoto = pd.read_excel('REPRESENTATIVIDADE DE ESCOLAS RURAIS SEM ESGOTO.xlsx')

esgoto.head(27)

estados = esgoto['ESTADOS']
qtd_rurais = esgoto['QTD DE ESCOLAS RURAIS']
qtd_sem_esgoto = esgoto['SEM ESGOTO']

largura_barra = 0.45
indices = np.arange(len(estados))

plt.bar(indices, qtd_rurais, largura_barra, label='Escolas Rurais')
plt.bar(indices + largura_barra, qtd_sem_esgoto, largura_barra, label='Rurais sem esgoto')

plt.xlabel('ESTADOS')
plt.ylabel('ESCOLAS')
plt.title('Comparação de Escolas Rurais e Escolas Rurais sem Esgoto')
plt.xticks(indices + largura_barra / 2, estados, rotation=45)  # Rótulos no eixo x (com rotação para melhor legibilidade)
plt.legend()

plt.tight_layout()
plt.show()

