# -*- coding: utf-8 -*-
"""Escolas por Estado OKOK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJk_TP_rsm52kASYundVY52p1OWaSYXt
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#carregando arquivos do PC
from google.colab import files
uploaded = files.upload()

escolas = pd.read_excel('EscolasMun.xlsx')

escolas.shape

escolas.head(27)

plt.figure(figsize=(10, 6))
plt.bar(escolas['Estados'], escolas['Municípios'])
plt.xlabel('Estados')
plt.ylabel('Quantidade de escolas')
plt.title('Contagem de Escolas por Estado')
plt.legend(fontsize=16)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#carregando arquivos do PC
from google.colab import files
uploaded = files.upload()

estaduais = pd.read_excel('EE_ESTADO.xlsx')

estaduais.shape

estaduais.head(27)

plt.figure(figsize=(10, 6))
plt.bar(estaduais['Estados'], estaduais['Estaduais'])
plt.legend(fontsize=16)
plt.xlabel('ESTADOS')
plt.ylabel('QTDE DE ESCOLAS ESTADUAIS')
plt.title('ESCOLAS ESTADUAIS POR ESTADO')

publicas = pd.read_excel('Municipai e estaduais.xlsx')

publicas.head(27)

plt.figure(figsize=(10, 6))
plt.bar(publicas['ESTADO'], publicas['ESCOLAS MUN/EST'])
plt.xlabel('ESTADOS')
plt.ylabel('QTDE DE ESCOLAS ESTADUAIS E MUNICIPAIS')
plt.title('ESCOLAS ESTADUAIS E MUNICIPAIS POR ESTADO')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

municipais = pd.read_excel('EscolasMun.xlsx')

municipais.shape

municipais.head(27)

plt.figure(figsize=(10, 6))
plt.bar(municipais['Estados'], municipais['Municípios'])
plt.xlabel('ESTADOS')
plt.ylabel('QTDE DE ESCOLAS MUNICIPAIS')
plt.title('ESCOLAS MUNICIPAIS POR ESTADO')

