# -*- coding: utf-8 -*-
"""Escolas Rurais por Estado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tzcCVL7S18sO-kQlNNr_zp3B9clZA2Yw
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

rural = pd.read_excel("RURAL.xlsx")

rural.head(27)

plt.figure(figsize=(10, 6))
plt.bar(rural['ESTADOS'], rural['QTD DE ESCOLAS RURAIS'])
plt.xlabel('ESTADOS')
plt.ylabel('QTD DE ESCOLAS RURAIS')
plt.title('QTD DE ESCOLAS RURAIS NO BRASIL')

