# -*- coding: utf-8 -*-
"""Rural Alunos por escola

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UnGTrU9g8LsHftwY7uyKrv2UEZdzrAVP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.read_excel('rural alunos por escola.xlsx')

rural = pd.read_excel('rural alunos por escola.xlsx')

plt.figure(figsize=(10, 6))
plt.bar(rural['ESTADOS'], rural['ALUNOS POR ESCOLA'])
plt.xlabel('ESTADOS')
plt.ylabel('ALUNOS POR ESCOLA')
plt.title('Quantidade de Alunos rurais por escola no Brasil')

