# -*- coding: utf-8 -*-
"""SEM ESGOTO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nh1V62-BFISXmNy49DzBigpoFSGXr4y6
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

esgoto = pd.read_excel('ESGOTO INEXISTENTE.xlsx')

esgoto.head(27)

plt.figure(figsize=(10, 6))
plt.bar(esgoto['ESTADOS'], esgoto['ESGOTO INEXISTENTE'])
plt.xlabel('ESTADOS')
plt.ylabel('ESCOLAS SEM ESGOTO')
plt.title('ESCOLAS DO BRASIL SEM ESGOTO')

